<a href="https://colab.research.google.com/github/GTD2101-ACD-GA-AD22/python-ricardo-qm/blob/main/7.%20Ext%20Libs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bibliotecas Externas

En Python existen una gran cantidad de Bibliotecas Externas que podemos importar para nuestros proyectos. Estas bibliotecas contienen grandes cantidades de variables y de código que se peude reutilizar para nuestros proyectos.

In [4]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [5]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [6]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [7]:
math.log(32, 2)

5.0

In [8]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [9]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of x but the sign of y.
   

# Alias de un modulo

En muchas ocasiones los programadores prefieren utilizar un alias para módulos que por razones diversas no quieren manejar con su nombre nativo.

In [10]:
import math as mt

mt.pi

3.141592653589793

# Importando con la palabra clave from

La palabra clave from permite importar todo el módulo (no es comun hacer esto, aunque es posible) o importar algunos de los objetos del módulo (esto es más común).

In [11]:
from math import *

print(pi, log(32, 2))

3.141592653589793 5.0


In [12]:
from math import log, pi

from numpy import asarray

print(pi, log(32, 2))

3.141592653589793 5.0


# Submodulos

Es posible que dentro de un modulo tengamos acceso a otros submodulos.

In [13]:
import numpy

print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:]
     )

numpy.random is a <class 'module'>
it contains names such as... ['seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [14]:
# Roll 10 dice

rolls = numpy.random.randint(low=1, high=6, size=10)

rolls

array([2, 1, 3, 1, 5, 3, 5, 4, 5, 2])

In [15]:
type(rolls)

numpy.ndarray

In [16]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [17]:
rolls.mean()

3.1

In [18]:
help(rolls.mean)

Help on built-in function mean:

mean(...) method of numpy.ndarray instance
    a.mean(axis=None, dtype=None, out=None, keepdims=False, *, where=True)
    
    Returns the average of the array elements along given axis.
    
    Refer to `numpy.mean` for full documentation.
    
    See Also
    --------
    numpy.mean : equivalent function



In [19]:
help(numpy.ndarray.mean)

Help on method_descriptor:

mean(...)
    a.mean(axis=None, dtype=None, out=None, keepdims=False, *, where=True)
    
    Returns the average of the array elements along given axis.
    
    Refer to `numpy.mean` for full documentation.
    
    See Also
    --------
    numpy.mean : equivalent function



# Sobrecarga de operadores

La forma como atuan los diversos operadores en Python no siempre es la misma. Muchas veces depende de la biblioteca con la que estés trabajando.

In [20]:
[3, 4, 1, 2, 2, 1] + [10]

[3, 4, 1, 2, 2, 1, 10]

In [21]:
rolls + 10

array([12, 11, 13, 11, 15, 13, 15, 14, 15, 12])

In [22]:
# At which indices are the dice less than or equal to 3?
rolls <= 3

array([ True,  True,  True,  True, False,  True, False, False, False,
        True])

In [23]:
xlist = [[1,2,3],[2,4,6],]

# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [24]:
# Get the last element of the second row of our numpy array
x[1,-1]

6

In [28]:
# Get the last element of the second sublist of our nested list?
xlist[1][-1]

6

In [29]:
import tensorflow as tf
# Create two constants, each with value 1
a = tf.constant(1)
b = tf.constant(1)

# Add them together to get...
a + b

<tf.Tensor: shape=(), dtype=int32, numpy=2>